export const UserAUthConstants = {
  MIN_LENGTH: 1,
  MAX_LENGTH: 50,
  FIRST_NAME_REQUIRED: "First name is required",
  LAST_NAME_REQUIRED: "Last name is required",
  EMAIL_REQUIRED: "Email is required",
  VALID_EMAIL_ERROR: "Invalid email",
  PASSWORD_REQUIRED: "Password is required",
  PASSWORD_MIN_LENGTH: 6,
  USER_ALREADY_EXISTS: "User already exists",
  PASSWORD_LENGTH_ERROR: "Password must be atleast 6 characters long",
  SOMETHING_WENT_WRONG: "Something went wrong",
  USER_CREATED: "User created successfully",
  INVALID_CREDENTIALS: "Invalid credentials",
  SUCCESSFUL_LOGIN: "Login successful",
};
